; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; #[env:esp32-c3-devkitm-1]
; [env:esp32-dev]
; platform = espressif32@6.6.0
; #board = esp32-c3-devkitm-1
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; monitor_filters = direct


; lib_deps =
;     knolleary/PubSubClient@2.8
;     bblanchon/ArduinoJson@7.4.2
;    # https://github.com/pschatzmann/arduino-audio-tools.git
; 	https://github.com/pschatzmann/arduino-libhelix.git



[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include

lib_ldf_mode = deep


lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    https://github.com/pschatzmann/arduino-libhelix.git